In [ ]:
""" create 2d list """

s = 'abcdef'
p = 'xyz'

# this creates a len(p) x len(s) 2d matrix (col x row)
V = [[s[i]+p[j] for j in range(len(p))] for i in range(len(s))]
# when indexing, the index for the outter list comprehension (in this case, for len(s)) comes before the index for the inner list comprehension (in this case, for len(p))
i = 3
j = 2
V[i][j]

# if creating by this way, there would be in fact only one list; changing [i][j] would affect all rows
# becasue python uses shallow list instantiaion
V2 = [[0] * len(p)] * len(s)

### use 'or' operator in variable assignments
* equivalent to conditional assignments

In [ ]:
""" use or operator in assignments """

# if a is not 0 or None, then x = a
a = 10
b = 12
x = a or b
print('x: {}'.format(x))

# otherwise y = d
c = 0
d = 12
y = c or d
print('y: {}'.format(y))

In [ ]:
""" 
np.nan_to_num 
- replaces NaN, posinf, neginf with definitive numbers
- by default NaN=0.0
"""

import numpy as np

np.nan_to_num(np.nan)

In [14]:
"""
np.clip(a, a_min, a_max)
- clip the values of an array into between the interval [a_min, a_max]
"""

import numpy as np

a = np.arange(10)
print(a)
b = np.clip(a, 2, 7)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 7 7]


array([0.])

### modules
* need to add a __init__.py file (could be empty) under a folder to make it an importable Python module

### *args, **kwargs
* these are common idioms in Python to allow arbitrary number of arguments and keyword-argument pairs to be passed to a function
* refer to [this post](https://stackoverflow.com/questions/36901/what-does-double-star-asterisk-and-star-asterisk-do-for-parameters) for details

common use cases:
* 1) allow a function to accept any number of arguments
    * can be used with other fixed arguments together
* 2) unpack the list of arguments

### dict.get(key) instead of dict[key]
* former method is preferred as it would return a default value for the key if the key is not present; second method would just raise a ValueError
* check [this answer](https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey) for details